Add home work 1
DimaKobets/Frontend pull request #1
Opened 2018-06-05 10:49 UTC by DimaKobets

2018-06-05 11:07 UTC, vkhmelko-softheme requested changes

2018-06-05 11:07 UTC, vkhmelko-softheme commented on internship2018-1/src/assets/bundle.js
> +/******/ (function(modules) { // webpackBootstrap
please remove this file from repo. Because it's autogenerated

2018-06-08 21:02 UTC, DimaKobets commented
bundle is removed

2018-06-10 08:44 UTC, vkhmelko-softheme commented
320 files changed! Not bad, not bad :)

2018-06-10 09:04 UTC, vkhmelko-softheme commented
![xina-resolutions](https://user-images.githubusercontent.com/4602989/41200047-12e406ec-6ca6-11e8-8df0-0a4120439ecf.png)

Your home task looks pretty good. Seems you know some html and css. Do you have any experience with bootstrap? Because what I need is only one item on the line for mobile devices and only 3 items for tablets and lager screens. 

Something line this:
![fireshot capture 3 - hello world - http___localhost_8081_products html](https://user-images.githubusercontent.com/4602989/41200061-5895da30-6ca6-11e8-9f33-b06030f3be45.png)
![fireshot capture 4 - hello world - http___localhost_8081_products html](https://user-images.githubusercontent.com/4602989/41200062-59e30ade-6ca6-11e8-8e43-c432aa6ca73c.png)

Try to use bootstrap. I'm sure it will be easy for you

2018-06-13 09:00 UTC, vkhmelko-softheme approved these changes

2018-06-14 09:02 UTC, merged

2018-06-14 10:16 UTC, dchecherynda-softheme commented on Homeworks/HW 2/filterArray.js
> +    else{
The else statement should be placed on the same line as the closing curly brace:

if (expression) {
    ...
} else {
    ...
}

2018-06-14 10:21 UTC, dchecherynda-softheme commented on Homeworks/HW 2/filterArray.js
> +        arrayOfKeys[i] = obj[key];
The **arrayofKeys** should contain keys of an object, not values - arrayOfKeys[i] = key;